// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:my_store/core/common_models/models/product_response_local_model.dart';
import 'package:my_store/features/address/data/models/address_local_model.dart';
import 'package:my_store/features/ai/data/model/ai_message_local_entity.dart';
import 'package:my_store/features/ai/data/model/conversation_local_model.dart';
import 'package:my_store/features/auth/data/models/customer_local_model.dart';
import 'package:my_store/features/cart/data/models/cart_local_model.dart';
import 'package:my_store/features/category/data/models/category_local_model.dart';
import 'package:my_store/features/orders/data/models/order_list_local_mode.dart';
import 'package:my_store/features/orders/data/models/order_review_local_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddressItemLocalModelAdapter());
    registerAdapter(AddressLocalModelAdapter());
    registerAdapter(AddressResponseLocalModelAdapter());
    registerAdapter(AiMessageLocalModelAdapter());
    registerAdapter(CalculatedPriceModelAdapter());
    registerAdapter(CartItemLocalModelAdapter());
    registerAdapter(CartLocalModelAdapter());
    registerAdapter(CartResponseLocalModelAdapter());
    registerAdapter(CategoryLocalModelAdapter());
    registerAdapter(CategoryResponseLocalModelAdapter());
    registerAdapter(ConversationLocalModelAdapter());
    registerAdapter(CustomerLocalModelAdapter());
    registerAdapter(CustomerOrderLocalModelAdapter());
    registerAdapter(CustomerResponseLocalModelAdapter());
    registerAdapter(OrderItemLocalModelAdapter());
    registerAdapter(OrderLocalModelAdapter());
    registerAdapter(OrderReviewItemLocalModelAdapter());
    registerAdapter(OrderReviewLocalModelAdapter());
    registerAdapter(OrderReviewResponseLocalModelAdapter());
    registerAdapter(OrdersResponseLocalModelAdapter());
    registerAdapter(ProductItemModelsAdapter());
    registerAdapter(ProductResponseLocalModelAdapter());
    registerAdapter(ShippingAddressLocalModelAdapter());
    registerAdapter(VariantModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddressItemLocalModelAdapter());
    registerAdapter(AddressLocalModelAdapter());
    registerAdapter(AddressResponseLocalModelAdapter());
    registerAdapter(AiMessageLocalModelAdapter());
    registerAdapter(CalculatedPriceModelAdapter());
    registerAdapter(CartItemLocalModelAdapter());
    registerAdapter(CartLocalModelAdapter());
    registerAdapter(CartResponseLocalModelAdapter());
    registerAdapter(CategoryLocalModelAdapter());
    registerAdapter(CategoryResponseLocalModelAdapter());
    registerAdapter(ConversationLocalModelAdapter());
    registerAdapter(CustomerLocalModelAdapter());
    registerAdapter(CustomerOrderLocalModelAdapter());
    registerAdapter(CustomerResponseLocalModelAdapter());
    registerAdapter(OrderItemLocalModelAdapter());
    registerAdapter(OrderLocalModelAdapter());
    registerAdapter(OrderReviewItemLocalModelAdapter());
    registerAdapter(OrderReviewLocalModelAdapter());
    registerAdapter(OrderReviewResponseLocalModelAdapter());
    registerAdapter(OrdersResponseLocalModelAdapter());
    registerAdapter(ProductItemModelsAdapter());
    registerAdapter(ProductResponseLocalModelAdapter());
    registerAdapter(ShippingAddressLocalModelAdapter());
    registerAdapter(VariantModelAdapter());
  }
}
